### ISSUE TITLE
iOS Error on get, version 3.0.0rc2

### ISSUE THREAD

**Issue by mberenguer-adding** [f-23/react-native-passkey#50]
I am using this library to authenticate to my .NET api using Fido2.AspNet. With version 2 it worked okay but I am testing new version to use new architecture.

I am getting this error on iOS:
```
Error {"error": "Native error", "message": "Error: Swift.DecodingError.keyNotFound(CodingKeys(stringValue: \"transports\", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: \"allowCredentials\", intValue: nil), _JSONKey(stringValue: \"Index 0\", intValue: 0)], debugDescription: \"No value associated with key CodingKeys(stringValue: \\\"transports\\\", intValue: nil) (\\\"transports\\\").\", underlyingError: nil))"}
```
The response I'm getting from my API is the following:
```
{"allowCredentials": [{"id": "1Gq80bsAZBoN3VjyYOEEfNXboGY", "type": "public-key"}], "challenge": "1doyzGTeFgolCwCyMwOMRi8XRvzCjlMg7Hcjivv_QRA", "errorMessage": "", "rpId": "***", "status": "ok", "timeout": 60000, "userVerification": "discouraged"}
```
(I change rpId with * but there was the domain on that property and it is correct)

As you wanted feedback following new rc on iOS, I let these logs so we can get to the final release without errors.

Thanks in advance.

**Comment by mberenguer-adding** [comment]
OK, so I found looking at swift code that if I set property transports to null as follows, it just works:
```js
res.allowCredentials = res.allowCredentials.map((cred) => {
  return {
    id: cred.id,
    type: cred.type,
    transports: null
  }
})
```
I guess it could be set by default if it's not needed. I'm going to test it on Android now. Let's see if everything works.
Thanks for all your efforts creating this library.

**Comment by f-23** [comment]
Thank you for the feedback, I'll resolve it for the 3.0 release!

**Comment by f-23** [comment]
@mberenguer-adding Could you confirm this is fixed for you in 3.0?

**Comment by mberenguer-adding** [comment]
Oh sorry. I'm from Valencia and there have been problems with floods. As soon as I can, I will test this.

**Comment by nicolinho22** [comment]
I've updated our app from Expo SDK 51 to 52 and this issue has returned. Updating to v3.1.0 didn't solve the issue.

Setting `transports: null` solves the problem. The following native error appears when using `transports: ['usb', 'hybrid', 'internal', 'nfc', 'smart-card']`:

`Error: Swift.DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: \"allowCredentials\", intValue: nil), _CodingKey(stringValue: \"Index 0\", intValue: 0), CodingKeys(stringValue: \"transports\", intValue: nil), _CodingKey(stringValue: \"Index 2\", intValue: 2)], debugDescription: \"Cannot initialize AuthenticatorTransport from invalid String value internal\", underlyingError: nil))`

**Comment by f-23** [comment]
@nicolinho22 The problem lies in the ASAuthentication framework on iOS only accepting `ble`, `nfc` and `usb` as possible transports values. I'm not sure why they decided to ignore the W3C recommendation, but to work around the decoding issue for now you would have to avoid using any other value for transports.
I'll take a look at how this can best prevented in the future, like using a default for the unsupported values, although I'm not sure which one would be best suited.
